spring:
  cloud:
    azure:
      storage:
        blob:
          container-name: ${BLOB_STORAGE_CONTAINER_NAME}
          connection-string: ${BLOB_STORAGE_CONNECTION_STRING}
  datasource:
    # Never put the db login credentials in your application code. Use placeholder like this.
    url:  ${DATASOURCE_URL} #
    username: ${DATASOURCE_USERNAME} # admin username of MySQL -> Secret from Azure Key Vault
    password: ${DATASOURCE_PASSWORD}  # password of admin of MySQL -> Secret from Azure Key Vault
  jpa:
    hibernate:
      ddl-auto: none # Turn off the DDL auto generation.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  web:
    resources:
      add-mappings: true