spring:
  datasource:
    # Never put the db login credentials in your application code. Use placeholder like this.
    url:  ${DATASOURCE_URL} #
    username: ${DATASOURCE_USERNAME} # admin username of MySQL -> Secret from Azure Key Vault
    password: ${DATASOURCE_PASSWORD}  # password of admin of MySQL -> Secret from Azure Key Vault
  jpa:
    hibernate:
      ddl-auto: none # Turn off the DDL auto generation.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  web:
    resources:
      add-mappings: true
  server:
    port: 80
